import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from 'react'
import io from 'Socket.IO-client'

let socket

export default function Home() {
  useEffect(() => getSocket(), [])
  const [id, setId] = useState()
  const [armed, setArmed] = useState()
  const [users, setUsers] = useState([])
  const [doorlog, setDoorLog] = useState()

  const armSystem = () => {
    socket.emit('armSystem')
  }

  const getSocket = async () => {
    await fetch('/api/socket')
    socket = io()
    socket.on('connect', () => {
      console.log("connected!")
    })
    socket.on('disconnect', () => {
      console.log(socket.id)
    })
    socket.on('updateId', (msg) => {
      setId(msg)
    })
    socket.on('armedSystem', (msg) => {
      setArmed(msg)
    })
    socket.on('getUsers', (msg) => {
      setUsers(msg)
    })
    socket.on('getDoorLog', (msg) => {
      // console.log(msg)
      setDoorLog(msg)
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>{id}</h1>
        <button style={{ backgroundColor: `${armed ? 'hsl(340deg 100% 32%)' : 'green'}` }} onClick={() => armSystem()} className={styles.pushable}>
          <span className={styles.shadow}></span>
          <span className={styles.edge}></span>
          <span style={{ backgroundColor: `${armed ? 'red' : 'hsl(119deg 100% 32%)'}` }} className={styles.front}>
            {armed ? 'Arm System' : 'Disarm System'}
          </span>
        </button>

        <button style={{ backgroundColor: `hsla(176, 38%, 70%)`, margin: 25 }} className={styles.pushable}>
          <span className={styles.shadow}></span>
          <span className={styles.edge}></span>
          <span style={{ backgroundColor: 'lightblue' }} className={styles.front}>
            Send Ping
          </span>
        </button>

        <div className={styles.grid} style={{ marginTop: 100 }}>
          <button style={{
            position: 'relative', left: 80, top: -120, borderRadius: 100, border: 'none', color: 'blue', padding: 5,
          }}>Clear Logs</button>
          <div className={styles.card} style={{ overflowY: 'scroll' }}>
            <h4>Door Log</h4>
            <ul style={{ padding: 0, listStyleType: 'none' }}>
              {
                doorlog?.map((test, i) => (
                  <li key={i} style={{ marginBottom: 10 }}>
                    System <span>{test.armed ? <b>armed</b> : <b>disarmed</b>}</span> by {test.id} ({test.time})
                  </li>
                ))
              }
            </ul>
          </div>

          <div className={styles.card} >
            <h4>Users Online</h4>
            <ul style={{ padding: 0, listStyleType: 'none' }}>
              {users.map((test, i) => <li key={i}>{test}</li>)}
            </ul>
          </div>
        </div>

      </main >
    </div >
  )
}
