import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from 'react'
import io from 'Socket.IO-client'

let socket

export default function Home() {
  useEffect(() => getSocket(), [])
  const [id, setId] = useState()
  const [armed, setArmed] = useState()

  const armSystem = () => {
    console.log('armed?')
    socket.emit('armSystem')
  }

  const getSocket = async () => {
    await fetch('/api/socket')
    socket = io()
    socket.on('connect', () => {
      console.log("connected!")
    })
    socket.on('updateId', (msg) => {
      setId(msg)
    })
    socket.on('armedSystem', (msg) => {
      setArmed(msg)
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>{id} has joined</h1>
        <button style={{ backgroundColor: `${armed ? 'hsl(340deg 100% 32%)' : 'green'}` }} onClick={() => armSystem()} className={styles.pushable}>
          <span style={{ backgroundColor: `${armed ? 'red' : 'hsl(119deg 100% 32%)'}` }} className={styles.front}>
            {armed ? 'Arm System' : 'Disarm System'}
          </span>
        </button>
      </main>
    </div>
  )
}
